### ISSUE TITLE
Change Data Capture support SQL Server 2019 Linux??

### ISSUE THREAD

**Issue by igcalvo** [microsoft/mssql-docker#453] opened 2019-05-14 15:11 UTC
Is anyone able to enable CDC at table level? At DB level is fine but not able to do it at table level.

SQL Server 2019 
Docker 
Linux CentOS

"Could not update the metadata that indicates table DBO.TABLENAME is enabled for Change Data Capture. The failure occurred when executing the command '[sys].[sp_cdc_add_job] @job_type = N'capture''. The error returned was 22836: 'Could not update the metadata for database DB to indicate that a Change Data Capture job has been added. The failure occurred when executing the command 'sp_add_jobstep_internal'. The error returned was 14234: 'The specified '@srv' is invalid (valid values are returned by sp_helpserver).'. Use the action and error to determine the cause of the failure and resubmit the request.'. Use the action and error to determine the cause of the failure and resubmit the request."

**Comment by forkazmoden** [comment] 2019-05-15 03:24
Hi,

I tried it on my SQL Server 2019 (CTP2.2) container and it worked. Here is my script.

```
create database test

use test
go
EXEC sys.sp_cdc_enable_db  
GO  

CREATE TABLE dbo.MyTable (EmployeeID int
PRIMARY KEY CLUSTERED);
go

EXEC sys.sp_cdc_enable_table  
@source_schema = N'dbo',  
@source_name   = N'MyTable',  
@role_name     = N'MyRole',  
@filegroup_name = N'Primary',  
@supports_net_changes = 1  
GO  

select name, is_tracked_by_cdc from sys.tables     --check whether a source table has already been enabled for change data capture
```
Result:

> Job 'cdc.test_capture' started successfully.
> Job 'cdc.test_cleanup' started successfully.

```
name                                              is_tracked_by_cdc
------------------------------- -----------------
systranschemas                                    0
change_tables                                     0
ddl_history                                       0
lsn_time_mapping                                  0
captured_columns                                  0
index_columns                                     0
MyTable                                           1
dbo_MyTable_CT                                    0
```

**Comment by igcalvo** [comment] 2019-05-15 08:02
wow awesome! thx  forkazmoden....I may be missing some thing else.

**Comment by igcalvo** [comment] 2019-05-15 08:25
@forkazmoden: are you using a Linux container right?

Following your steps I got this error and the DB is CDC enabled....

Could not update the metadata that indicates table [dbo].[MyTable] is enabled for Change Data Capture. The failure occurred when executing the command '[sys].[sp_cdc_add_job] @job_type = N'capture''. The error returned was 22836: 'Could not update the metadata for database test to indicate that a Change Data Capture job has been added. The failure occurred when executing the command 'sp_add_jobstep_internal'. The error returned was 14234: 'The specified '@srv' is invalid (valid values are returned by sp_helpserver).'. Use the action and error to determine the cause of the failure and resubmit the request.'. Use the action and error to determine the cause of the failure and resubmit the request.


select name, is_cdc_enabled from sys.databases:

name	is_cdc_enabled
test	            1

**Comment by forkazmoden** [comment] 2019-05-15 08:28
Yes, I was using a Linux container.

```
select @@version

result:
Microsoft SQL Server 2019 (CTP2.2) - 15.0.1200.24 (X64) 
	Dec  5 2018 16:51:26 
	Copyright (C) 2018 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS) <X64>

(1 row affected)
```

**Comment by igcalvo** [comment] 2019-05-15 08:29
Thank you @forkazmoden will keep searching for a fix.

**Comment by forkazmoden** [comment] 2019-05-15 08:36
I used to see similar error message when try to enable CDC on normal SQL Server instance. It is caused by the mismatch of server name. You can run the following query to check that.

```
select SERVERPROPERTY('ServerName')
select * from master.dbo.sysservers
```

**Comment by igcalvo** [comment] 2019-05-15 08:47
You are crack.... it was exactly that... for some reason there were different names in sys.servers table. 
So the steps to fix it

select SERVERPROPERTY('ServerName') : Correct_Server_Name
select srvname from master.dbo.sysservers: Old_Server_Name

the fix:

EXEC sp_DROPSERVER 'Old_Server_Name'
EXEC sp_ADDSERVER 'Correct_Server_Name', 'local'

at it works! 

Thx a lot @forkazmoden !

**Comment by forkazmoden** [comment] 2019-05-15 08:49
Glad to hear that:-) If the issue has been resolved, you can close this thread.

**Comment by igcalvo** [comment] 2019-05-15 08:50
Closing.

**Closed** 2019-05-15 08:50 UTC
