### ISSUE TITLE
Unable to connect from outside container to sql server

### ISSUE THREAD

**Issue by schneckm** [microsoft/mssql-docker#688] opened 2021-05-18 13:36 UTC
I created a docker container from image mssql-server-windows-developer:latest. After the container was up I connected by cli and executed sqlcmd. This worked find. Now I wanted to connect from windows 10 host with SSMS to sql container and this failed with network related error message. I tried with localhost and also with IP address. The container was started with parameter -p 1433:1433

I tried same with a linux container and sql server. This worked fine. I was able to connect with SSMS from host to container.

Why is the connection with SSMS from windows 10 host to windows sql server container not working ?

**Comment by amvin87** [comment] 2021-05-18 14:41
It should not have failed, please ensure that the ports are opened on the host from where you are running the windows container.

**Comment by schneckm** [comment] 2021-05-18 14:59
I used the same port (1433) in a linux container with sql server 2017 on same host after I stopped the windows container and switched to linux. This worked fine. So the port must be open on the host side.
I assumed that SQL Server in windows container doesn't allow remote connections. I remember this was the case in the past when installiing developer edition; the remote connections must be allowed explicit. I also checked for sql server configuration manager, but this is a GUI tool. I couldn't find a configuration tool which can be run from cli.

**Comment by schneckm** [comment] 2021-05-19 07:41
I don't mean sql server to sql server communication. I mean the tool to configure network protocols. With sql server configuration manager it is possible to enable and disable protocols. I wanted to check this configuration in the container but the tool is a GUI tool. I attched a screenshot of that tool from a development server. Is there another way to check SQL Server network configuration from cli?
![Sql Server Configuration Manager](https://user-images.githubusercontent.com/56295356/118772018-85cd8f80-b883-11eb-8303-aa4e4673823a.png)

**Comment by schneckm** [comment] 2021-05-20 07:01
I did some checks and it seems the issue is on Windows 10 host network. I did a ping to the windows container and even this didn't work. I will search for additional info to get the network fixed.

Thank you for your valuable input.

**Comment by adam-wheeler-tfs** [comment] 2021-05-20 23:22
I'm having the same issue, I have tried this image, I have tried building from windowsservercore too. the only thing that works is linux but for what I am doing I need windows. 

I'll post here if I figure something out.

**Comment by schneckm** [comment] 2021-05-27 11:30
I now found the root cause for my issue:
The issue only happens when I'm connected to company network with VPN. If I do not open a VPN channel then I'm able to connect to SQL Server in container from the host.
I'm wondering that with SQL Server in linux container this issue doesn't appear. To this SQL Server I'm able to connect from host without and with VPN. I'm wondering that Docker seems to behave different between those two OS related to network.

So before starting work I have to decide what I want to do ? Working with Windows SQL Server container or working in company network. This is not really a good solution.

**Comment by adam-wheeler-tfs** [comment] 2021-05-27 13:34
@schneckm Is your computer Windows or Linux? On windows I found that the only way I could connect is if I use the containers ip address. Are you using localhost,1433 in SMSS on windows to connect?

**Comment by adam-wheeler-tfs** [comment] 2021-05-27 16:50
@francisco-marin Check this out. I wonder if this helps. with our issue. we may need to look into split tunneling for the 172.26 subnet.

**Comment by adam-wheeler-tfs** [comment] 2021-05-27 17:03
So. I can confirm that I cannot connect when on a vpn. I also had to disable ipv6 for another app that I have installed in Docker.

**Comment by adam-wheeler-tfs** [comment] 2021-05-27 18:00
@schneckm This looks like it is one of two issues. Either the vpn is forcing all traffic through the vpn, this can be fixed with split tunneling. Or the vpn is trying to use the same ip range as docker, this can be fixed with configuration in docker. See [here](https://www.lullabot.com/articles/fixing-docker-and-vpn-ip-address-conflicts) this might help. Ultimately though this really has nothing to do with MSSQL

**Comment by amvin87** [comment] 2021-05-28 21:20
At this point, I don't think this is an issue with MSSQL, looks to be a networking issues with VPN enabled. For now closing this issue but if you still think it is SQL Server issue, we can reopen it back.

**Closed by amvin87** 2021-05-28 21:20 UTC
