### ISSUE TITLE
Error on using an NFS mounted directory for volume mapping

### ISSUE THREAD

**Issue by upadhyayap** [Microsoft/mssql-docker#150] opened 2017-08-18 12:26 UTC
I am using microsoft/mssql-server-linux latest tagged docker image to run mssql server container. It is running fine when i map a host dir inside container with -v option. For some reasons like growing database size and swarm i do not want to persist data onto my docker host. Instead i have a NFS mounted dir on the docker host which will be mapped as a volume inside container. Now when i do that my container does not starts and gives following error.

2017-08-18 12:09:49.33 spid5s      Starting up database 'master'.
2017-08-18 12:09:49.34 Server      Software Usage Metrics is disabled.
2017-08-18 12:09:49.49 spid5s      Error: 17204, Severity: 16, State: 1.
2017-08-18 12:09:49.49 spid5s      FCB::Open failed: Could not open file /var/opt/mssql/data/master.mdf for file number 1.  OS error: 87(The parameter is incorrect.).
2017-08-18 12:09:49.49 spid5s      Error: 5120, Severity: 16, State: 101.
2017-08-18 12:09:49.49 spid5s      Unable to open the physical file "/var/opt/mssql/data/master.mdf". Operating system error 87: "87(The parameter is incorrect.)".
2017-08-18 12:09:49.64 spid5s      Error: 17204, Severity: 16, State: 1.
2017-08-18 12:09:49.64 spid5s      FCB::Open failed: Could not open file /var/opt/mssql/data/mastlog.ldf for file number 2.  OS error: 87(The parameter is incorrect.).
2017-08-18 12:09:49.64 spid5s      Error: 5120, Severity: 16, State: 101.
2017-08-18 12:09:49.64 spid5s      Unable to open the physical file "/var/opt/mssql/data/mastlog.ldf". Operating system error 87: "87(The parameter is incorrect.)".
 

I have given full access rights to all the mdf and ldf files to see if that is the problem but no help there.

I am running container like below

docker run -it -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=no password here' -p 1433:1433 -v /var/nfs/database/data:/var/opt/mssql/data microsoft/mssql-server-linux:latest

where /var/nfs is a NFS mount on the host output of df -h -T is below.
SomeIp:/var/nfs nfs4      443G   47G  375G  11% /var/nfs

**Comment by twright-msft** [comment] 2017-08-18 14:33
This is a known issue in RC1/RC2.  Please use :ctp2-1 for now. The issue is fixed and will be available in the next public release.

**Comment by perrysk-msft** [comment] 2017-10-13 19:57
@upadhyayap - This issue should be fixed by pulling the latest mssql server Linux image:

[microsoft/mssql-server-linux] (https://hub.docker.com/r/microsoft/mssql-server-linux/)

**Comment by upadhyayap** [comment] 2017-10-18 12:10
@twright-msft @perrysk-msft yes this issue is resolved with latest image. Thank's a lot.

**Closed** 2017-10-18 14:10 UTC
Labels: mssql-server-linux
