### ISSUE TITLE
SqlPackage tool in Linux image

### ISSUE THREAD

**Issue by sixeyed** [Microsoft/mssql-docker#185] opened 2017-10-20 10:32 UTC
This is a feature request. The Windows SQL Server image provides the SqlPackage tool, it would be great to have that in the Linux image too. 

With SqlPackage you can build your own Docker image on top of SQL Server, packaging your schema in a Dacpac (see [this Dockerfile example](https://github.com/docker/labs/blob/master/windows/sql-server/Dockerfile.v1)). Then with a startup script (like [this](https://github.com/docker/labs/blob/master/windows/sql-server/Initialize-Database.ps1)) you can have a database image that supports running a new database, or attaching existing data files and upgrading the schema.

**Comment by twright-msft** [comment] 2017-10-20 19:43
Thanks for the feature suggestion!  This is in progress.  There are a few steps we have to go through to get this back into the Linux image.  Closing as a dupe of https://github.com/Microsoft/mssql-docker/issues/135

**Closed by twright-msft** 2017-10-20 19:43 UTC

**Comment by thesushil** [comment] 2018-01-30 12:44
Is there any ETA of this feature?

**Comment by twright-msft** [comment] 2018-01-30 21:58
Pretty soon.  We are in testing phase now...

**Comment by nigel-dewar** [comment] 2018-06-22 11:09
Hi There, is this implemented yet? I cannot see it is searching around in mid 2018

**Comment by twright-msft** [comment] 2018-06-22 15:45
@nigel-dewar  - see this issue: #135
