### ISSUE TITLE
Run scripts in /docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by zippy1981** [Microsoft/mssql-docker#36] opened 2017-02-20 21:38 UTC
This probably requires that odbc tools be added to the image. However, both the official [postgres](https://hub.docker.com/_/postgres/) and [mysql](https://hub.docker.com/_/mysql/) images will execute any sql scripts in that folder. This makes it very easy to spin up an instance with, your schema already defined. Its also really good if you want to add some scripts like [sp_WhoIsActive](http://sqlblog.com/blogs/adam_machanic/archive/tags/sp_5F00_whoisactive/default.aspx), [Ola's maintenance script](https://ola.hallengren.com/downloads.html)., or [Brent's scripts](https://www.brentozar.com/blitz/) to docker images.

**Comment by sbarne3** [comment] 2017-02-20 22:53
this is pretty much the same as #2 and #4

**Comment by twright-msft** [comment] 2017-02-28 05:43
@zippy1981 
As I understand your request this is a duplicate of #11 
Please reopen if you are looking for something different.

**Closed by twright-msft** 2017-02-28 05:43 UTC
